server:
  port: 9599
spring:
  application:
    name: EventTracker
  datasource:
    generate-unique-name: false
    name: eventTracker
    url: jdbc:mysql://localhost:3306/eventTracker
    username: user
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always