CREATE TABLE IF NOT EXISTS Clients (
	id			INT AUTO_INCREMENT PRIMARY KEY,
	name		VARCHAR(50) NOT NULL,
	password	VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS Events (
	id				INT			AUTO_INCREMENT PRIMARY KEY,
	creator_id		INT			NOT NULL,
	name			VARCHAR(50) NOT NULL,
	start_datetime	DATETIME,
	end_datetime	DATETIME
);


CREATE TABLE IF NOT EXISTS Entries (
	id				INT AUTO_INCREMENT PRIMARY KEY,
	parttaker_id	INT NOT NULL,
	event_id		INT NOT NULL
);